
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  batch:
    job:
      enabled: false



location:
    base: /home/maiconsa/Documentos/batchFiles/
